language: python
python: "2.7"
services: mongodb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  - "python application.py &"
  - sleep 3 
  - mkdir ".webassets-cache"

install: "pip install -r requirements.txt --use-mirrors"

script: 
  - "python tests.py"
  - "phantomjs jasmine_runner.js http://localhost:5000/static/SpecRunner.html"
  - "python db/import_data/import_job.py"
  - "lettuce"
