language: python
python: "2.7"
services: mongodb

env:
  global:
    - "ARTIFACTS_AWS_REGION=us-west-2"
    - "ARTIFACTS_S3_BUCKET=unicefuganda-devtrac2"
    - DEVTRAC_ENV=Testing
    - secure: "ND7CWMc8ai3hpn9KIw8tp14qFkqmiogZqNW0mCIWinaAs/ID+AYUuTjIYwaTnd3bx4+JMwkedSV3Ql+k87TgloRxazT0AGBciU+9QOwra6XBNLJUuAChIJ5U1z3x17e6mE0K52KPNH1l1fNMy30M1gIugkVWPTeIsvSBwfOLiFs="
    - secure: "U7hVXMdAF4KHT63k4hYuwG4JSmCoiS1V2zuXDATEQT1vHT7zlendLYMJpd9l57e46x69/Yc7Z+gQhyoTl5CBpMtH5JbxGR9Geg9GVogwB44dyMbFhBUoDJtFf7njSwiaL4TeCyq8fIwBBWbplTcSxjJK9Ej5x+dgMViZhFOC5Sc="

before_script:
  - "gem install travis-artifacts"
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 
  - "twistd web --port 5000 --wsgi application.app"
  - sleep 3 
  - mkdir ".webassets-cache"

install: "pip install -r requirements.txt --use-mirrors"

script: 
  - "python tests.py"
  - "phantomjs jasmine_runner.js http://localhost:5000/static/SpecRunner.html"
  - "python db/import_data/import_job.py"
  - "lettuce"

after_failure: # this will of course run only on failure
  - "travis-artifacts upload --path *.png"
